In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.read_csv("50_Startups.csv")

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
X = df.iloc[:, :4].values

In [5]:
y = df.iloc[:, -1].values

In [6]:
ct = ColumnTransformer(transformers= [("encoder", OneHotEncoder(), [3])], remainder="passthrough")

In [7]:
X = ct.fit_transform(X)

In [8]:
X[:5]

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42]], dtype=object)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0 )

In [11]:
X_train, X_test, y_train, y_test

(array([[0.0, 1.0, 0.0, 55493.95, 103057.49, 214634.81],
        [0.0, 0.0, 1.0, 46014.02, 85047.44, 205517.64],
        [0.0, 1.0, 0.0, 75328.87, 144135.98, 134050.07],
        [1.0, 0.0, 0.0, 46426.07, 157693.92, 210797.67],
        [0.0, 1.0, 0.0, 91749.16, 114175.79, 294919.57],
        [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
        [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
        [0.0, 0.0, 1.0, 1000.23, 124153.04, 1903.93],
        [0.0, 0.0, 1.0, 542.05, 51743.15, 0.0],
        [0.0, 0.0, 1.0, 65605.48, 153032.06, 107138.38],
        [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
        [0.0, 1.0, 0.0, 61994.48, 115641.28, 91131.24],
        [1.0, 0.0, 0.0, 63408.86, 129219.61, 46085.25],
        [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
        [1.0, 0.0, 0.0, 23640.93, 96189.63, 148001.11],
        [1.0, 0.0, 0.0, 76253.86, 113867.3, 298664.47],
        [0.0, 0.0, 1.0, 15505.73, 127382.3, 35534.17],
        [0.0, 0.0, 1.0, 120542.52, 148718.95, 3

In [12]:
from sklearn.linear_model import LinearRegression
rg = LinearRegression()

rg.fit(X_train, y_train)

LinearRegression()

In [13]:
y_pred = rg.predict(X_test)


In [14]:
y_pred

array([103015.20159796, 132582.27760815, 132447.73845175,  71976.09851259,
       178537.48221056, 116161.24230166,  67851.69209676,  98791.73374687,
       113969.43533013, 167921.06569551])

In [15]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [16]:
np.set_printoptions(precision = 2)

In [17]:
sum((y_test.reshape(len(y_test), 1) - y_pred.reshape(len(y_pred), 1)) ** 2)

array([8.35e+08])